HE-Arc/rapport-technique

- .travis.yml
- rapport.md
```
** WARNING ** Failed to convert input string to UTF16...
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\TeX ->\TeX 
\xspace 
```
sad
> upgrade pandoc to 2.2

- .travis.yml
> bump pandoc(-crossref) versions

- .travis.yml
> travis: pandoc 2.6

- .travis.yml
give it a try (crossref will probably fail)
> pandoc 2.7.3

- .travis.yml
I've been told that xenial is everywhere now.
> travis: bump to xenial

- .gitlab-ci.yml
- README.md
En 2019, GitLab est plus que jamais intéressant.
https://gitlab.com/greut/rapport-technique/merge_requests/1
> gitlab-ci: first shot

- .gitlab-ci.yml
- .travis.yml
- https://github.com/jgm/pandoc/releases/tag/2.8
- https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.5.0
> travis: pandoc 2.8

- .travis.yml
https://github.com/jgm/pandoc/releases/tag/2.10
> travis: use pandoc 2.10

- rapport.md
> rapport: pandoc 2.10

- .gitlab-ci.yml
- .travis.yml
> chore: upgrade pandoc-crossref

- .gitlab-ci.yml
- .travis.yml
- Makefile
- rapport.md
> feat: use integrated citeproc

- .travis.yml
> feat: build on focal

- .travis.yml
it's failing because of the _markdown_ file.
> fix: disable jekyll

- README.md
> feat: add Tom Pollard thesis template

- .gitlab-ci.yml
- .travis.yml
> chore: bump pandoc from 2.11.3.2 to 2.11.4

- .gitlab-ci.yml
- .travis.yml
> chore: bump pandoc from 2.11.4 to 2.12

- .travis.yml
> fix: main branch is main

- .gitlab-ci.yml
- .travis.yml
> chore: bump pandoc from 2.12 to 2.13

- .travis.yml
> chore: bump Pandoc from 2.14.0.1 to 2.14.2

- .travis.yml
> chore: bump Pandoc from 2.14.2 to 2.16.2
